---
- name: Install dependencies
  ansible.builtin.package:
    name: "{{ locale_dependencies }}"
    state: present

- name: Ensure a locale exists
  community.general.locale_gen:
    name: "{{ locale }}"
    state: "{{ locale_state }}"